// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import {
  Address,
  DataSourceTemplate,
  DataSourceContext
} from "@graphprotocol/graph-ts";
import {dataSource} from '@graphprotocol/graph-ts/common/datasource'
import {log} from '@graphprotocol/graph-ts/'

export class PoolContract extends DataSourceTemplate {

  static _create(address: Address): void {
    log.debug("NIK template: creating template Pool with adr : {} ", [address.toHex()])
    DataSourceTemplate.create("Pool", [address.toHex()]);
    log.debug("NIK template: pool created with address : {} ", [address.toHex()])

  }

  static _createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext("Pool", [address.toHex()], context);
  }
}

export class CrpControllerContract extends DataSourceTemplate {
  static _create(address: Address): void {
    DataSourceTemplate.create("CrpController", [address.toHex()]);
  }

  static _createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext(
      "CrpController",
      [address.toHex()],
      context
    );
  }
}
